
# Cover
cover: !include covers.yaml

# Elero
elero:
    transmitters:
        - transmitter_id: 1
          port: '/dev/ttyUSB0'
          
# Group
group: !include groups.yaml

# Weather prediction
sensor: !include sensors.yaml
