  - platform: elero
    covers:
        bathroom_small:
            name: Zuhanyzo
            channel:
                - 1
            device_class: roller shutter
            supported_features:
                - up
                - down
                - stop
        guestroom:
            name: Vendeg
            channel:
                - 2
            device_class: roller shutter
            supported_features:
                - up
                - down
                - stop
        childrenroom:
            name: Gergo
            channel:
                - 3
            device_class: venetian blind
            supported_features:
                - up
                - down
                - stop
                - tilt
        bathroom_big:
            name: Furdo
            channel:
                - 4
            device_class: venetian blind
            supported_features:
                - up
                - down
                - stop
                - tilt
        bedroom:
            name: Halo
            channel:
                - 5
            device_class: venetian blind
            supported_features:
                - up
                - down
                - stop
                - tilt
        livingroom:
            name: Nappali
            channel:
                - 6
            device_class: venetian blind
            supported_features:
                - up
                - down
                - stop
                - tilt
        diningroom:
            name: Etkezo
            channel:
                - 7
            device_class: venetian blind
            supported_features:
                - up
                - down
                - stop
                - tilt

  - platform: group
    name: "Mind"
    entities:
        - cover.zuhanyzo
        - cover.vendeg
        - cover.gergo
        - cover.furdo
        - cover.halo
        - cover.nappali
        - cover.etkezo

  - platform: group
    name: "Nappal"
    entities:
        - cover.zuhanyzo
        - cover.gergo
        - cover.halo
        - cover.nappali
        - cover.etkezo

  - platform: group
    name: "Utcafront"
    entities:
        - cover.zuhanyzo
        - cover.vendeg

  - platform: group
    name: "Kelet"
    entities:
        - cover.gergo

  - platform: group
    name: "Del"
    entities:
        - cover.furdo
        - cover.halo
        - cover.nappali

  - platform: group
    name: "Nyugat"
    entities:
        - cover.nappali
        - cover.etkezo

  - platform: group
    name: "K-D-Ny"
    entities:
        - cover.gergo
        - cover.furdo
        - cover.halo
        - cover.nappali
        - cover.etkezo
